name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: '0 13 * * *'

jobs:
  merge_schedule:
    runs-on: ubuntu-22.04
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          merge_method: squash
          time_zone: 'Europe/London'
          # Require all pull request statuses to be successful before
          # merging. Default is `false`.
          require_statuses_success: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}